### ISSUE TITLE
github.com/charmbracelet/lipgloss: invalid version: unknown revision 6304a734e792

### ISSUE THREAD

**Issue by Dr-Terrible** [caarlos0/log#3]
When downloading `github.com/caarlos0/log@v0.1.5`, `go get` complains about a missing dependency:

> go get -v -u github.com/caarlos0/log@v0.1.5
go: downloading github.com/caarlos0/log v0.1.5
go: downloading github.com/charmbracelet/lipgloss v0.6.1-0.20220911181249-6304a734e792
github.com/caarlos0/log imports
	github.com/charmbracelet/lipgloss: github.com/charmbracelet/lipgloss@v0.6.1-0.20220911181249-6304a734e792: invalid version: unknown revision 6304a734e792
	
Indeed, GitHub confirms that the URL https://github.com/charmbracelet/lipgloss/commit/6304a734e7929d2eac85fdcabcd3a66ed3899c3a is not available:
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Erasing the module cache (go clean -modcache) and then upgrading all my modules is what triggered the missing dependency.

My `go env`:
> GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/****/.cache/go-build"
GOENV="/home/****/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/****/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/****/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"

**Comment by caarlos0** [comment]
ah, it was using lipgloss from a pr - that is now merged, not sure why its complaining now.

anyway, update to master.

**Comment by Dr-Terrible** [comment]
I hate to bring bad news, but `go get` is still complaining about missing dependencies; this time is termenv:
> go get -v -u github.com/caarlos0/log@v0.1.7
get "gopkg.in/yaml.v3": found meta tag vcs.metaImport{Prefix:"gopkg.in/yaml.v3", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v3"} at //gopkg.in/yaml.v3?go-get=1
get "gopkg.in/check.v1": found meta tag vcs.metaImport{Prefix:"gopkg.in/check.v1", VCS:"git", RepoRoot:"https://gopkg.in/check.v1"} at //gopkg.in/check.v1?go-get=1
go: downloading github.com/caarlos0/log v0.1.7
go: downloading github.com/charmbracelet/lipgloss v0.6.1-0.20221011104340-92c8fa0a572b
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/muesli/reflow v0.3.0
go: downloading github.com/muesli/termenv v0.12.1-0.20220901123159-d729275e0977
go: downloading github.com/rivo/uniseg v0.4.2
get "golang.org/x/sys": found meta tag vcs.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys?go-get=1
github.com/caarlos0/log imports
	github.com/charmbracelet/lipgloss imports
	github.com/muesli/termenv: github.com/muesli/termenv@v0.12.1-0.20220901123159-d729275e0977: invalid version: unknown revision d729275e0977
	
Same thing as before, `go.mod` points to a non-existing commit: https://github.com/muesli/termenv/commit/d729275e0977
